(()=>{
'use strict';
const MODES={
 shield:{title:'반향 방파제',tag:'01 / FACE THE PRESSURE',color:'#67e2d2',intro:'향하는 방향이 방패입니다. 전방을 지키고, 자세를 굳혀 사방의 공격을 되돌리세요.',tip:'이동 방향을 방어합니다. 정면 충돌/탄환은 막고 반격합니다. Space는 1.2초 전방위 방어 자세입니다.',ability:'방어 자세',up:[['넓은 방패','전방 방어 각도 +20도','arc'],['강한 반향','막기 피해 +1','reflect'],['빠른 자세','자세 대기 -0.6초','cooldown']]},
 bond:{title:'빚빛 채집꾼',tag:'02 / CARRY THE RISK',color:'#ffb47b',intro:'조각을 들고 있으면 화력과 적 압박이 함께 커집니다. 언제 정산할지 결정하세요.',tip:'처치 후 조각을 줍습니다. 조각 4개마다 사격 피해+1, 보유가 많을수록 적이 자주 옵니다. Space 정산은 보상을 확정하고 8개당 생명1을 회복합니다. 피격하면 일부 미정산 조각을 잃습니다.',ability:'조각 정산',up:[['조각 증폭','조각 3개마다 피해+1','charge'],['빠른 정산','정산 대기 -0.6초','cooldown'],['안전 계약','피격 조각 손실 감소','insurance']]},
 polar:{title:'극성 행진',tag:'03 / SHAPE THE MATCH',color:'#b4acff',intro:'원과 마름모 적을 보고 극성을 바꾸세요. 같은 극성에는 자동 사격이 강해집니다.',tip:'현재 극성은 ○ 또는 ◇로 표시됩니다. 같은 극성 적에 피해3, 다른 적에는 피해1입니다. Space로 전환하고 새 극성의 파동을 보냅니다.',ability:'극성 전환',up:[['깊은 공명','같은 극성 피해+1','match'],['넓은 파동','전환 파동 반경+25','radius'],['빠른 전환','전환 대기 -0.5초','cooldown']]}
};
const key=new URLSearchParams(location.search).get('game'),modeKey=MODES[key]?key:'shield',m=MODES[modeKey],$=id=>document.getElementById(id);
document.body.dataset.mode=modeKey;document.title=m.title+' | 심다 LAB';$('modeEyebrow').textContent=m.tag;$('modeTitle').textContent=m.title;$('modeIntro').textContent=m.intro;$('actionLabel').textContent=m.ability;$('abilityLabel').textContent=m.ability;$('touchAction').textContent=m.ability;document.querySelectorAll('[data-game-link]').forEach(a=>{if(a.dataset.gameLink===modeKey)a.classList.add('active')});
const canvas=$('arena'),ctx=canvas.getContext('2d'),wrap=document.querySelector('.arena-wrap');let W=900,H=550,z=1,state=null,last=performance.now(),keys=new Set(),audio=null,sound=false;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),rand=(a,b)=>a+Math.random()*(b-a);
function resize(){const r=wrap.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);W=r.width;H=r.height;z=clamp(Math.min(W/900,H/550),.55,1.2);canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0);if(state){state.p.x=clamp(state.p.x,15,W-15);state.p.y=clamp(state.p.y,15,H-15)}}new ResizeObserver(resize).observe(wrap);resize();
function tone(f=500){if(!sound)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.value=f;g.gain.setValueAtTime(.025,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.12)}catch{}}
function overlay(title,text,button='시작하기'){ $('overlayKicker').textContent=m.tag;$('overlayTitle').textContent=title;$('overlayText').textContent=text;$('primaryButton').textContent=button;$('overlayHint').textContent='이동 WASD/방향키/화면 클릭 · Space 능력 · P 일시정지';$('overlay').hidden=false;$('liveStatus').textContent=title+'. '+text;$('primaryButton').focus() }
overlay(m.title,m.intro+'\n'+m.tip+'\n60초 동안 살아남으세요.');
function start(){state={p:{x:W/2,y:H/2,hp:6,face:0,inv:0},t:0,status:'play',kills:0,level:1,xp:0,need:5,enemies:[],bullets:[],hostile:[],drops:[],fx:[],spawn:.5,fire:.2,target:null,cd:0,brace:0,blockCd:0,blocked:0,cargo:0,bank:0,polarity:0,upgrade:{arc:0,reflect:0,cooldown:0,charge:0,insurance:0,match:0,radius:0},notice:'',noticeLife:0,wave:0};keys.clear();last=performance.now();$('overlay').hidden=true;$('upgradePanel').hidden=true;canvas.focus();announce('작전 시작. 60초 생존!');hud()}
function announce(text){if(!state)return;state.notice=text;state.noticeLife=1.8;$('liveStatus').textContent=Math.ceil(60-state.t)+'초 남음. '+text;tone()}
function finish(win){state.status=win?'won':'lost';keys.clear();$('upgradePanel').hidden=true;overlay(win?'60초 생존 성공':'작전 실패',(win?'처치 '+state.kills+' · 레벨 '+state.level:'생명이 소진됐습니다. 이동과 능력 타이밍을 바꿔보세요.')+(modeKey==='bond'?'\n확정 조각 '+state.bank+' · 미정산 '+state.cargo:'')+'\nR 키 또는 버튼으로 다시 시작합니다.','다시 시작')}
$('primaryButton').onclick=()=>{if(state?.status==='paused'){state.status='play';$('overlay').hidden=true;last=performance.now();canvas.focus()}else start()};$('soundButton').onclick=()=>{sound=!sound;$('soundButton').textContent=sound?'소리 켬':'소리 끔';$('soundButton').setAttribute('aria-pressed',String(sound));tone(700)};
function ability(){const s=state;if(!s||s.status!=='play'||s.cd>0)return;
 if(modeKey==='shield'){s.brace=1.2;s.cd=Math.max(1.8,4.2-s.upgrade.cooldown*.6);announce('전방위 방어 자세 1.2초');}
 if(modeKey==='bond'){if(s.cargo===0){announce('정산할 조각이 없습니다. 먼저 조각을 주우세요.');return}const gained=s.cargo;s.bank+=gained;s.cargo=0;s.p.hp=Math.min(6,s.p.hp+Math.floor(gained/8));s.cd=Math.max(2,5.2-s.upgrade.cooldown*.6);for(const e of s.enemies)if(dist(e,s.p)<115*z)hit(e,3);announce('조각 '+gained+'개 정산 · 보상 확정');}
 if(modeKey==='polar'){s.polarity=1-s.polarity;s.cd=Math.max(1.2,3.3-s.upgrade.cooldown*.5);const r=(110+s.upgrade.radius*25)*z;for(const e of s.enemies)if(dist(e,s.p)<r){if(e.polarity===s.polarity)hit(e,3+s.upgrade.match);const a=Math.atan2(e.y-s.p.y,e.x-s.p.x);e.x+=Math.cos(a)*40*z;e.y+=Math.sin(a)*40*z}announce((s.polarity?'◇ 마름모':'○ 원')+' 극성 전환');}
 s.fx.push({x:s.p.x,y:s.p.y,r:modeKey==='polar'?(110+s.upgrade.radius*25)*z:100*z,life:.4,max:.4});}
function level(){const s=state;s.level++;s.xp-=s.need;s.need=6+s.level*3;s.status='upgrade';keys.clear();$('upgradeChoices').replaceChildren();m.up.forEach((c,i)=>{const b=document.createElement('button'),k=document.createElement('kbd'),h=document.createElement('strong'),p=document.createElement('span');k.textContent=i+1;h.textContent=c[0];p.textContent=c[1];b.append(k,h,p);b.onclick=()=>choose(i);$('upgradeChoices').append(b)});$('upgradePanel').hidden=false;$('upgradeChoices').querySelector('button').focus();$('liveStatus').textContent='레벨 '+s.level+'. 숫자1~3 또는 버튼으로 성장 선택';}
function choose(i){const s=state;if(!s||s.status!=='upgrade'||!m.up[i])return;s.upgrade[m.up[i][2]]++;s.status='play';$('upgradePanel').hidden=true;last=performance.now();canvas.focus();announce(m.up[i][0]+' 선택');}
function spawn(){const s=state,edge=Math.floor(Math.random()*4);let x=rand(0,W),y=rand(0,H);if(edge===0)x=-20;if(edge===1)x=W+20;if(edge===2)y=-20;if(edge===3)y=H+20;const ranged=s.t>10&&Math.random()<.24,polarity=Math.random()<.5?0:1,hp=ranged?3:s.t>35?3:2;s.enemies.push({x,y,r:(ranged?12:10)*z,hp,max:hp,speed:(ranged?38:60+s.t*.4)*z,ranged,shoot:rand(1,3),polarity,dead:false,bump:0});}
function hit(e,d){if(e.dead)return;e.hp-=d;spark(e.x,e.y);if(e.hp<=0){e.dead=true;const s=state;s.kills++;s.xp++;if(modeKey==='bond')s.drops.push({x:e.x,y:e.y,life:20});if(s.kills%18===0&&s.p.hp<6){s.p.hp++;announce('처치 보상 · 생명1 회복')}if(s.xp>=s.need&&s.status==='play')level();}}
function spark(x,y){state.fx.push({x,y,r:18*z,life:.2,max:.2})}
function front(x,y){const p=state.p,a=Math.atan2(y-p.y,x-p.x);let diff=Math.atan2(Math.sin(a-p.face),Math.cos(a-p.face));return Math.abs(diff)<Math.PI/3+state.upgrade.arc*Math.PI/18;}
function block(x,y,e){const s=state;if(modeKey!=='shield'||s.blockCd>0||!(s.brace>0||front(x,y)))return false;s.blockCd=.4;s.blocked++;spark(s.p.x,s.p.y);if(e){hit(e,1+s.upgrade.reflect);const a=Math.atan2(e.y-s.p.y,e.x-s.p.x);e.x+=Math.cos(a)*55*z;e.y+=Math.sin(a)*55*z;e.bump=.3}announce('방어 성공 · '+s.blocked+'회');return true;}
function hurt(){const s=state;if(s.p.inv>0)return;s.p.hp--;s.p.inv=.85;if(modeKey==='bond'){const lost=Math.ceil(s.cargo*Math.max(.12,.35-s.upgrade.insurance*.1));s.cargo=Math.max(0,s.cargo-lost);announce('피격 · 생명 '+s.p.hp+' · 조각 '+lost+'개 손실')}else announce('피격 · 생명 '+s.p.hp);if(s.p.hp<=0)finish(false);}
function fire(){const s=state,p=s.p;let nearest=null,best=Infinity;for(const e of s.enemies){const d=dist(e,p);if(!e.dead&&d<best){best=d;nearest=e}}if(!nearest)return;const a=Math.atan2(nearest.y-p.y,nearest.x-p.x);s.bullets.push({x:p.x,y:p.y,vx:Math.cos(a)*420*z,vy:Math.sin(a)*420*z,life:2,polarity:s.polarity});}
function update(dt){const s=state,p=s.p;s.t+=dt;s.cd=Math.max(0,s.cd-dt);s.brace=Math.max(0,s.brace-dt);s.blockCd=Math.max(0,s.blockCd-dt);s.noticeLife=Math.max(0,s.noticeLife-dt);p.inv=Math.max(0,p.inv-dt);
 const wave=Math.floor(s.t/20);if(wave>s.wave){s.wave=wave;announce('파동 '+(wave+1)+' · 적 압박 증가')}
 let dx=0,dy=0;if(keys.has('w')||keys.has('arrowup'))dy--;if(keys.has('s')||keys.has('arrowdown'))dy++;if(keys.has('a')||keys.has('arrowleft'))dx--;if(keys.has('d')||keys.has('arrowright'))dx++;
 if(dx||dy)s.target=null;else if(s.target){dx=s.target.x-p.x;dy=s.target.y-p.y;if(Math.hypot(dx,dy)<6){s.target=null;dx=dy=0}}
 const len=Math.hypot(dx,dy);if(len){p.face=Math.atan2(dy,dx);p.x=clamp(p.x+dx/len*172*z*dt,14*z,W-14*z);p.y=clamp(p.y+dy/len*172*z*dt,14*z,H-14*z)}
 s.spawn-=dt;const pressure=modeKey==='bond'?1+Math.min(s.cargo,30)*.025:1;if(s.spawn<=0){spawn();s.spawn=Math.max(.26,.95-s.t*.008)/pressure}
 s.fire-=dt;if(s.fire<=0){fire();s.fire=.45;}
 for(const e of s.enemies){if(e.dead)continue;e.bump=Math.max(0,e.bump-dt);const d=dist(e,p),a=Math.atan2(p.y-e.y,p.x-e.x);if(e.bump<=0&&(!e.ranged||d>165*z)){e.x+=Math.cos(a)*e.speed*dt;e.y+=Math.sin(a)*e.speed*dt}if(e.ranged){e.shoot-=dt;if(e.shoot<=0){s.hostile.push({x:e.x,y:e.y,vx:Math.cos(a)*125*z,vy:Math.sin(a)*125*z,life:5});e.shoot=2.4}}
  if(d<e.r+12*z){if(!block(e.x,e.y,e))hurt();if(s.status!=='play')return;}}
 for(const b of s.bullets){if(b.life<=0)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;for(const e of s.enemies){if(!e.dead&&dist(e,b)<e.r+4*z){const damage=modeKey==='bond'?2+Math.floor(s.cargo/(s.upgrade.charge?3:4)):modeKey==='polar'?(b.polarity===e.polarity?3+s.upgrade.match:1):2;hit(e,damage);b.life=0;if(s.status!=='play')return;break}}}
 for(const b of s.hostile){if(b.life<=0)continue;b.x+=b.vx*dt;b.y+=b.vy*dt;b.life-=dt;if(dist(b,p)<15*z){if(!block(b.x,b.y)){hurt()}else{const e=s.enemies.find(e=>!e.dead&&dist(e,p)<220*z);if(e)hit(e,2+s.upgrade.reflect)}b.life=0;if(s.status!=='play')return;}}
 for(const d of s.drops){d.life-=dt;const len=dist(d,p);if(len<230*z){const a=Math.atan2(p.y-d.y,p.x-d.x);d.x+=Math.cos(a)*250*z*dt;d.y+=Math.sin(a)*250*z*dt}if(len<16*z){s.cargo++;d.life=0}}
 for(const f of s.fx)f.life-=dt;s.enemies=s.enemies.filter(e=>!e.dead);s.bullets=s.bullets.filter(b=>b.life>0);s.hostile=s.hostile.filter(b=>b.life>0);s.drops=s.drops.filter(d=>d.life>0);s.fx=s.fx.filter(f=>f.life>0);if(s.t>=60&&s.status==='play')finish(true);}
function circle(x,y,r,c){ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fillStyle=c;ctx.fill()}
function shape(x,y,r,pol,c){ctx.fillStyle=c;if(pol===0)circle(x,y,r,c);else{ctx.beginPath();ctx.moveTo(x,y-r);ctx.lineTo(x+r,y);ctx.lineTo(x,y+r);ctx.lineTo(x-r,y);ctx.closePath();ctx.fill()}}
function render(){ctx.fillStyle='#091d2d';ctx.fillRect(0,0,W,H);ctx.strokeStyle='#193647';ctx.lineWidth=1;for(let x=0;x<W;x+=44*z){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,H);ctx.stroke()}for(let y=0;y<H;y+=44*z){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(W,y);ctx.stroke()}if(!state)return;const s=state,p=s.p;
 for(const e of s.enemies){const c=modeKey==='polar'?(e.polarity?'#ffc276':'#9eceff'):'#ec8595';shape(e.x,e.y,e.r,e.polarity,c);if(e.ranged){ctx.strokeStyle='#fff2d0';ctx.lineWidth=2;ctx.strokeRect(e.x-e.r,e.y-e.r,e.r*2,e.r*2)}circle(e.x,e.y,2.3*z,'#202d49')}
 for(const d of s.drops)shape(d.x,d.y,5*z,1,'#ffe1a3');for(const b of s.bullets)circle(b.x,b.y,3.5*z,m.color);for(const b of s.hostile)circle(b.x,b.y,5*z,'#ffcc86');
 for(const f of s.fx){ctx.globalAlpha=f.life/f.max;ctx.strokeStyle=m.color;ctx.lineWidth=3*z;ctx.beginPath();ctx.arc(f.x,f.y,f.r*(1-f.life/f.max*.5),0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1}
 if(modeKey==='shield'){ctx.strokeStyle=s.brace>0?'#f3fff8':'#6be6d8';ctx.lineWidth=5*z;ctx.beginPath();ctx.arc(p.x,p.y,24*z,s.brace>0?0:p.face-Math.PI/3-s.upgrade.arc*Math.PI/18,s.brace>0?Math.PI*2:p.face+Math.PI/3+s.upgrade.arc*Math.PI/18);ctx.stroke()}
 if(p.inv>0&&Math.floor(p.inv*14)%2===0)ctx.globalAlpha=.45;shape(p.x,p.y,13*z,modeKey==='polar'?s.polarity:0,m.color);circle(p.x+Math.cos(p.face)*6*z,p.y+Math.sin(p.face)*6*z,3*z,'#fff');ctx.globalAlpha=1;
 ctx.textAlign='center';ctx.font='bold '+(12*z+2)+'px system-ui';ctx.fillStyle='#e7f6ff';if(modeKey==='polar')ctx.fillText(s.polarity?'◇':'○',p.x,p.y-23*z);if(modeKey==='bond')ctx.fillText('보유 '+s.cargo,p.x,p.y-22*z);
 if(s.noticeLife>0){ctx.fillStyle='#082233df';ctx.fillRect(12,12,W-24,34);ctx.fillStyle='#edfaff';ctx.font='bold 14px system-ui';ctx.fillText(s.notice,W/2,34,W-40)}ctx.textAlign='left';ctx.fillStyle='#bdd4e2';ctx.font='12px system-ui';ctx.fillText('파동 '+(s.wave+1)+' / 생명 '+p.hp+'/6',14,H-14);}
function hud(){if(!state)return;const s=state,remaining=Math.max(0,Math.ceil(60-s.t));$('timeValue').textContent=String(Math.floor(remaining/60)).padStart(2,'0')+':'+String(remaining%60).padStart(2,'0');$('healthValue').textContent=s.p.hp+' / 6';$('levelValue').textContent=s.level;$('killValue').textContent=s.kills;$('xpText').textContent=s.xp+' / '+s.need;$('xpFill').style.width=clamp(s.xp/s.need*100,0,100)+'%';$('specialLabel').textContent=modeKey==='shield'?'방어 성공':modeKey==='bond'?'미정산 / 확정 조각':'현재 극성';$('specialText').textContent=modeKey==='shield'?s.blocked+'회':modeKey==='bond'?s.cargo+' / '+s.bank+' · 피해 '+(2+Math.floor(s.cargo/(s.upgrade.charge?3:4)))+' · 압박 ×'+(1+Math.min(s.cargo,30)*.025).toFixed(2):(s.polarity?'◇ 마름모':'○ 원');$('specialFill').style.width=(modeKey==='bond'?Math.min(100,s.cargo/30*100):modeKey==='shield'?Math.min(100,s.blocked*5):s.polarity?100:50)+'%';$('abilityValue').textContent=s.cd>0?s.cd.toFixed(1)+'초 후':'준비됨';$('touchAction').textContent=m.ability+'\n'+(s.cd>0?s.cd.toFixed(1)+'초':'준비');}
function pause(){if(state?.status==='play'){state.status='paused';keys.clear();overlay('일시 정지','준비되면 같은 판을 이어서 플레이하세요.','계속하기')}else if(state?.status==='paused'){$('primaryButton').click()}}
window.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(state?.status==='upgrade'&&['1','2','3'].includes(k)){choose(+k-1);return}if(k==='p'){pause();return}if(k==='r'&&['lost','won'].includes(state?.status)){start();return}if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(k===' '){if(!e.repeat)ability();return}keys.add(k)});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();if(state?.status==='play')pause()});document.addEventListener('visibilitychange',()=>{keys.clear();if(document.hidden&&state?.status==='play')pause();last=performance.now()});
canvas.addEventListener('pointerdown',e=>{if(state?.status!=='play')return;const r=canvas.getBoundingClientRect();state.target={x:clamp(e.clientX-r.left,15,W-15),y:clamp(e.clientY-r.top,15,H-15)};canvas.focus()});document.querySelectorAll('[data-dir]').forEach(b=>{const k={up:'w',down:'s',left:'a',right:'d'}[b.dataset.dir];b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);keys.add(k)};for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,()=>keys.delete(k))});$('touchAction').onclick=ability;
function frame(now){const dt=Math.min((now-last)/1000,.05);last=now;if(state?.status==='play')update(dt);render();hud();requestAnimationFrame(frame)}requestAnimationFrame(frame);
})();
